brew install awscli
brew install azure-cli
brew install bash-completion@2
brew install bat
brew install broot
brew install cask
brew install docker
brew install eksctl
brew install exa
brew install ffmpeg
brew install findutils
brew install git
brew install gnu-sed
brew install grep
brew install groovy
brew install htop
brew install jq
brew install kind
brew install kustomize
brew install mas
brew install maven
brew install minikube
brew install moreutils
brew install ncdu
brew install openssl@3
brew install pass-otp
brew install pre-commit
brew install restic
brew install smimesign
brew install speedtest-cli
brew install starship
brew install telnet
brew install terraform
brew install tflint
brew install tldr
brew install wget
brew install youtube-dl
