tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "jpeg-xl"
brew "aom"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "broot"
brew "coreutils"
brew "gnutls"
brew "emacs"
brew "cask"
brew "docker"
brew "eksctl"
brew "exa"
brew "harfbuzz"
brew "gobject-introspection"
brew "python@3.9"
brew "libbluray"
brew "ffmpeg"
brew "findutils"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "grep"
brew "groovy"
brew "htop"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "kustomize"
brew "node"
brew "markdown-toc"
brew "mas"
brew "maven"
brew "minikube"
brew "moreutils"
brew "ncdu"
brew "neovim"
brew "openssl@3"
brew "tree"
brew "pass"
brew "pass-otp"
brew "pre-commit"
brew "restic"
brew "smimesign"
brew "speedtest-cli"
brew "starship"
brew "telnet"
brew "terraform"
brew "tflint"
brew "tldr"
brew "wget"
brew "yarn"
brew "youtube-dl"
cask "evernote"
cask "visual-studio-code"
cask "vlc"
mas "AdBlock", id: 1402042596
mas "Amphetamine", id: 937984704
mas "Grammarly for Safari", id: 1462114288
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Slack", id: 803453959
